//! Randomized differential fuzz: 400 pseudo-random non-control programs generated by
//! the Python reference. Requires identical final state, probed memory, and T-states.
use emu8085::{Addr, Cpu, Memory, SystemBus};
include!("common/fuzz_cases.rs");

fn run(prog: &[u8]) -> (Cpu, Memory, u64) {
    let mut cpu = Cpu::new();
    let mut mem = Memory::from_lines(16);
    let mut bus = SystemBus::default();
    mem.load_bytes(prog, Addr(0)).unwrap();
    cpu.start_at(Addr(0));
    let mut t = 0u64;
    while !cpu.is_halt && cpu.fault.is_none() && t < 200_000 {
        cpu.process(&mut bus);
        mem.step(&mut bus);
        t += 1;
    }
    (cpu, mem, t)
}

#[test]
fn fuzz_matches_reference() {
    for (i, case) in FUZZ.iter().enumerate() {
        let (cpu, mem, ticks) = run(case.prog);
        assert!(cpu.fault.is_none(), "fuzz #{i} faulted: {:?}", cpu.fault);
        let e = &case.exp;
        let got = (
            cpu.regs.a, cpu.regs.b, cpu.regs.c, cpu.regs.d, cpu.regs.e, cpu.regs.h, cpu.regs.l,
            cpu.regs.sp.0, cpu.flags.to_psw(), ticks, mem.read(Addr(0xF0)), mem.read(Addr(0xEF)),
        );
        let exp = (e.a, e.b, e.c, e.d, e.e, e.h, e.l, e.sp, e.psw, e.ticks, e.mf0, e.mef);
        assert_eq!(got, exp, "fuzz #{i} diverged (prog={:02X?})", case.prog);
    }
}
